# Generated by Django 4.0.4 on 2022-05-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_front', models.ImageField(blank=True, upload_to='images')),
                ('img_back', models.ImageField(blank=True, upload_to='images')),
            ],
            options={
                'db_table': 'myapp_image',
            },
        ),
    ]
